### ISSUE TITLE
Task 10 Is it OK to add some regularization terms?

### ISSUE THREAD

**Issue by zdchan** [cmm-21/a6#11]
Dear TA,

I add some triky regularizer to the objective function to make the spaceship fit the purple circle perfectly, is it a reasonable solution and could I get full points??

Thanks

**Comment by MiguelZamoraM** [comment]
Could you elaborate more on what you mean by tricky regularizer?

**Comment by zdchan** [comment]
> Could you elaborate more on what you mean by tricky regularizer?

What I mean is that, for example, add some regularizer to the velocity. The discretion of the velocity maybe not accurate enough, so my orbit is a bit elliptical without the regularizer, just as #8 said.

**Comment by MiguelZamoraM** [comment]
Sure. That sounds reasonable.
