### ISSUE TITLE
Q7 - Objective function

### ISSUE THREAD

**Issue by TunVunDerBunn** [cmm-21/a6#12]
Hi,

Can we retune the weights of the objective function for Q7 compared to Q4? With the weights from Q4 in the objective function, the target is not always reached in my case.

Thank you very much already in advance.

**Comment by MiguelZamoraM** [comment]
Sure thing. Although very similar those are in the end two different problems.

**Comment by TunVunDerBunn** [comment]
Okay perfect, thank you for the quick reply

**Comment by TunVunDerBunn** [comment]
Is it enough when Q7 only works with gradient descent. It is recommended to use gradient descent, but does that mean it does not have to work with newtons method?

**Comment by MiguelZamoraM** [comment]
It's indeed ok if it only works with gradient descent.

**Comment by TunVunDerBunn** [comment]
Thank you very much!
