### ISSUE TITLE
Question 10 epsilon too large

### ISSUE THREAD

**Issue by Zzyus** [cmm-21/a6#14]
Do we really need an epsilon = 0.01 in calculation of gravity? Considering r=0.5, even when x is on the orbit, (||x-sun|| + epsilon)^2 = 0.51^2 = 0.2601, which leads to a 3.8% error on the gravitational force. After changing epsilon to 1e-9, my trajectory got much better aligned with the orbit.

Another problem is the time step size. I manually set a perfect (x_k, v_k) at step k, but the simulated trajectory was still not as perfect as what's shown in the video due to the large step size. So, are we allowed to use a smaller h than 1/30, or will you consider this when grading?

Thanks in advance!

**Comment by MiguelZamoraM** [comment]
These are all very good considerations, which show your understanding of the problem. However, to ensure that everybody is solving the same problem I would encourage you to try to find a good solution without tuning those parameters. Of course, if you submit your approach with good justifications you are also gonna get credit.

**Comment by Zzyus** [comment]
Thanks for replying! Well, I somehow figured out the first problem without tuning epsilon ( although I am not sure if it is the right way to do it). But regarding the second issue, how can we make a perfect circle with semi-implicit Euler without reducing the step size? Could you give me a hint?

**Comment by MiguelZamoraM** [comment]
What do we want? We want the ship to stay in the orbit for a long time even if cut the thrusters after (K=32). Then the questions is, how can we formalize that notion of the ship staying in orbit using an objective that depends both on the state and the controls ? 
Hope this helps.

**Comment by Zzyus** [comment]
Yes, I get it now, thank you so much!
