### ISSUE TITLE
Constant objective function in Task8

### ISSUE THREAD

**Issue by luohwu** [cmm-21/a6#15]
Hi,
While implementing task8, I have tried different objective functions and output the final objective value. The final objective function is always constant, even though different objective functions have different values. And if I use gradient descent method, then this problem won't occur.  I really don't why this will happen.

**Comment by luohwu** [comment]
I have tried different weights for different cost. But the problem still occur

**Comment by MiguelZamoraM** [comment]
Hi. I couple of notes:

- In the objective function for the transcription app, you should somehow penalize deviations of the state trajectory x from the physics, and I don't see that in your objective.

- In the evaluate loop you are accessing elements beyond the size of the vectors. Inside the loop `for(int i=0;i<K;i++)` you are actually accessing element i+1 so in the last iteration it will get outside the range of the vectors.

- Do not print the objective inside the evaluate function. That function is called many times to evaluate the gradients and the hessian via finite differences. Use checkboxes in the GUI "PRINT O" and "PRINT "|G|" to print the value of the objective correctly. 

- Remember to run the app in release mode or release with debug info.

Let me know how it goes.

**Comment by luohwu** [comment]
HI Miguel,
Thank you so much for your help. So I think my way of penalizing deviations was not correct. So now I am using another method. And I have changed the `for` loop. However, I still got the same problem. So under debug mode, the function `evaluate` can be finished successfully.

**Comment by luohwu** [comment]
I have checked my commits history, and I think nothing else was changed by accident before.

**Comment by MiguelZamoraM** [comment]
The changes you made are not really penalizing deviations from a physical trajectory. But you are kind of on the right track.  Try to think how to get a kind of physically valid trajectory  x_bar and then apply an objective that penalizes a deviation from such trajectory.

**Comment by luohwu** [comment]
Ops. Thank you so much!!!. I will investigate more.

**Comment by MiguelZamoraM** [comment]
Hi @luohwu . I think I checked the wrong repo before I posted my previous answer. Sorry about that. You are already penalizing deviations from a physical trajectory. If you are still having issues try to add regularization on most of the things. Start with simple values like 1 and then try to tune that.

**Comment by luohwu** [comment]
Thank you so much. I regularized everything and now it's working.
