### ISSUE TITLE
Spaceship does not go around Planet

### ISSUE THREAD

**Issue by robindurkowitzer** [cmm-21/a6#18]
![grafik](https://user-images.githubusercontent.com/49153302/119168698-7a37bf80-ba61-11eb-9dd8-1c979e224a2b.png)
As we can see in the image, the thrusters just try to counteract the forces of the planet. After the 64 Timesteps, it will fly into and through the planet. 
I set the objective to be end Velocity = 0 at the end as well distance to the purple dot should be 0 as said in the write up.
Also I did not have to tune any weight for it to stop right at the position in question 4, which was as a little strange as well. 
Am I missing a constraint completely? 

If I drag the purple point around the planet, it will find a way to follow it but that is basically just getting stuck in the optimization...

**Comment by robindurkowitzer** [comment]
So I can reduce the Weight  of the velocity penalty by a lot and then the looping becomes quite easy, but of course the end velocity is quite large... is that the point ? 
![grafik](https://user-images.githubusercontent.com/49153302/119172871-bae60780-ba66-11eb-87e2-151c130c91ac.png)

**Comment by MiguelZamoraM** [comment]
As you can see in the video tutorial it's very difficult to stop right at the purple dot when you have a planet. But as long as you reach the target position in the last time step it's ok.

**Comment by robindurkowitzer** [comment]
Ok, so the last one is fine then? 
Thanks!
