### ISSUE TITLE
challenge App Optimization drifts to the Right

### ISSUE THREAD

**Issue by robindurkowitzer** [cmm-21/a6#19]
Hello, 
I tried implementing this Excercise.  And am getting closer. however during Optimization the trajectory keeps pushing more and more to the right. It looks like this: 
https://youtu.be/IbmWpCxZ1Wc

Could it just be a weight tuning issue, or is it more likely a Problem with my Objective Function ?

**Comment by MiguelZamoraM** [comment]
It's ok if it drifts  during optimization. What is really important for that task is that the ship remains in orbit after the thrusters are turned off.
