### ISSUE TITLE
Screen issue

### ISSUE THREAD

**Issue by vullnetu** [cmm-21/a6#2]
Hello 

I have a problem changing the target position of the little square "rocket", it lies on the edge or outside the window frame when I run the shooting app. the "i have screen issue" option doesn't help here.

<img width="721" alt="Screenshot 2021-05-14 at 16 54 25" src="https://user-images.githubusercontent.com/80257949/118289193-60343500-b4d5-11eb-931d-428b9f0989f2.png">

**Comment by MiguelZamoraM** [comment]
Could you try setting the default zoom from 1.f to .4f. See line: 

https://github.com/cmm-21/a6/blob/7428ad8b8481f9b1a42b793992173f0adee9db67/src/app/shooting-app.cpp#L248

Let me know if it helps.

**Comment by vullnetu** [comment]
Now I see both the square and the dot (target) but they are still at the edge. I have to manually make the window bigger, Can we somehow shift the whole thing? Moreover, dragging the target point is not working either.

**Comment by hkkkpang** [comment]
Same issue. Dragging the purple point doesn't work.

**Comment by vullnetu** [comment]
looks like something is wrong with the position of the mouse/ frame in general. If you print out the mouse position it is somewhere outside the frame.

**Comment by robin271828** [comment]
I have the same problem on my Mac, on ubuntu it seems to work...

**Comment by MiguelZamoraM** [comment]
This is probably a Mac specific problem and I don't have access to a Mac laptop right now.
I hope this issue won't prevent you from moving forward with the assignment.
I'll reach back to you tomorrow.  Sorry for the inconvenience.

**Comment by MiguelZamoraM** [comment]
Hi Please check the branch. https://github.com/cmm-21/a6/tree/mac-screen-issue

I change the default screen offset for the shooting-app and the transcription-app.
You can also change such offset from the gui and also the dragging should work.

Let me know if you have any trouble.

**Comment by swellsc** [comment]
Hi @MiguelZamoraM thanks for solving the issue for Mac! I had already made changes in my code before finding this issue, how can I add the changes of this branch to my code without losing my progress? Thanks a lot :)

**Comment by MiguelZamoraM** [comment]
I depends on how experienced you are with merging code. **First commit and push your changes**. Then make sure you are on the master branch and then do something like:

`git merge mac-screen-issue`

Of course you can always, just do some good old copy pasting by looking at the commit history.

**Comment by swellsc** [comment]
I'm not experienced at all. I tried what you suggested and got:
`fatal: refusing to merge unrelated histories`
So, is it an option for me to add my changes to the mac-screen-issue branch? As in, if my solutions are only added to that branch in the end, will they be found and evaluated correctly? Or should I keep trying to merge branches with main?

**Comment by MiguelZamoraM** [comment]
I think it's ok for you to put your changes in the mac branch. As long as you  write very clearly in the readme of the main branch that you pushed your code to the mac branch.

**Comment by swellsc** [comment]
Alright, I'll do that. Thank you!
