### ISSUE TITLE
Grading of Assignments

### ISSUE THREAD

**Issue by robindurkowitzer** [cmm-21/a6#20]
Since the Exam is coming up, I was wondering if we are going to be informed what our score on the assignments was. 
Also do you give partial points if there are functionalities partially implemented, or do only fully functioning solutions give points? 

Best Wishes!

**Comment by MiguelZamoraM** [comment]
I'll do my best to reach back to you all with the grades for this assignment as soon as possible after the deadline. Partial points will only be given for implementations that are close to fully functional.

**Comment by robindurkowitzer** [comment]
Thanks! 
Do you know if we also get feedback on the other Assignments? 

Also, will we get access to an example Solutions so we can learn how it should have been done if we were not able to get everything?
