### ISSUE TITLE
About question 5 in the writeup

### ISSUE THREAD

**Issue by Hustwireless** [cmm-21/a6#21]
The question 5 says 'How many steps does Newton's method usually take to converge for this probelm? Why?'

Are we supposed to analysis why it takes exactly this many steps, or do we just answer why we think it takes this many steps to converge, or do we answer why the newton's method converges so fast?

Thanks!

**Comment by zdchan** [comment]
I am also wondering about this. Should we find an exact number during which the Newton's method converges and explain the reason? Or it's just an approximate number and we just answer why the Newton's method converge faster?

**Comment by MiguelZamoraM** [comment]
You should optimize for a few different targets. Make an average of how many steps Newton's method takes and answer why you think that is a reasonable number of steps. You can also compare it with the number of steps Newton's method would take in a perfect setting.

**Comment by Hustwireless** [comment]
Thanks for the rapid answer! 
However, since it's not a second-order objective, e.g. x is cubic to u. I found it hard to give a mathematical explaination on how many steps it takes in ideal case. I feel that we could only say something regarding to limited significant digits. So I'm still confusing.

**Comment by MiguelZamoraM** [comment]
Well, the point is how many steps does it take for Newton's method to converge in a perfect setting? Can we expect to converge in such number of steps? Are we even in that perfect setting?  Hope this helps.
