### ISSUE TITLE
Transcription : optimizer crash on large constraints value?

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a6#23]
Hi,

I am trying to implement the transcription app. My problem is as such and could be related to issue #1 but I'm not sure :

I set 3 coefficients for each sub-objective : regularizer, physics and initial conditions. When I set these 3 coefficients to something low like 10^-3, the optimizer does not crash. Afterwards I gradually change these coefficients to something like 10^6 and then I get the same results as in the demo video.

However, if I start the optimization directly with coefficients like 10^6 then the optimizer will crash. Should I worry about fixing this? If so, I have no clue as to why this happens, so any insights would be helpful!

**Comment by MiguelZamoraM** [comment]
Ideally, you should find some fixed parameters that you can use to start the optimization from zero. But if this is not possible just make a .GIF  or something where you record the process you use to achieve a successful optimization and you should be more than fine. 

PS: I noticed in your readme that you put an image but you most likely forgot to push such image.

**Comment by lthiet** [comment]
That works, thanks!
