### ISSUE TITLE
About the weights in Question 4

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a6#25]
Dear TAs

In Question 4, we need to implement the objective funtion. Having 0 velocity at the end, and having the space ship at the goal position is, as I understand it, a hard constraint. Does this mean, that we don't need to add stage cost to the remaining stages? I am asking, because a hard constraint would either require only having weight on the terminal stage, or having an infinite weight on it (which would be an indicator function in a way). However, the infinite weight doesn't really work for me. Or do you want a pseudo hard constraint with just an insanely big weight? I spent a lot of time tuning weights and I realized I better ask what is expected for the hard constraints.

Thank you!

**Comment by MiguelZamoraM** [comment]
See the thread https://github.com/cmm-21/a6/issues/4#issue-892432305
