### ISSUE TITLE
task 10

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a6#26]
Hi,

This is by a long shot but, I am struggling a lot to get the last part of the task 10 working. I don't have a background in physics, so is there any resources I could read on to succeed in task 10? 

In the additional reading, I found a set of equations such that, if they are set to 0, then the particle should stay in orbit. I copy pasted these formulas into the objective function but only the position at the distance of orbit and the direction of the tangential velocity seems to work and I don't quite know what is missing..

**Comment by MiguelZamoraM** [comment]
So, one approach is to try to reach a certain target velocity and then hope for the best after the thrusters are turned off. But that is not really what we want. What we really want is for the ship to stay in orbit even after thrusters are off. Then it's all about specifying that in terms of an objective. 

PS: Take a look at threads in  https://github.com/cmm-21/a6/issues/14#issuecomment-845947773  and https://github.com/cmm-21/a6/issues/24#issue-899109628. I hope that helps as well.

**Comment by lthiet** [comment]
I managed to find a solution after your comments, it seems a bit brute force to me but perhaps I was on the wrong track the whole time. It is solved now, I hope, thanks!
