### ISSUE TITLE
Task 4 & 5: Gradient and Newton's Method

### ISSUE THREAD

**Issue by nwicki** [cmm-21/a6#27]
I think the way I implemented the objective function works quite well. However, I have some insecurities about the correctness of it. To show what I have so far, have a look at this video: https://youtu.be/vjmXVjy0cIo

The added regularizer improves the second order optimization very well, but I get the warning that the determinant of the Hessian is approximately zero and I don't know whether this is expected or a mistake in some way. Also, it slows down the gradient approach a bit as you can see in the video example. Is this still fast enough?

Task 5 asks to optimize for different targets with Newton's method. With targets you mean different positions of the purple target position right? Unfortunately, for some reason I cannot move the purple circle, is there a fix for it? Or is it enough if I just answer the question with the knowledge for a single target position?

Thanks for your support.

**Comment by MiguelZamoraM** [comment]
- It looks pretty ok to me. 

- Yes, we mean different positions of the purple dot.

- If you are using mac please check https://github.com/cmm-21/a6/issues/2#issue-891993131 and https://github.com/cmm-21/a6/tree/mac-screen-issue

**Comment by nwicki** [comment]
Yes, thanks. I actually had already merged with the branch "mac-screen-issue" but forgot to rerun cmake. Everything works now as expected.

Edit: Also, I forgot to mention that setting "I_AM_HAVING_SCREEN_ISSUES" to true did not allow me to move the purple target position.
