### ISSUE TITLE
Task 8: SIGSEGV

### ISSUE THREAD

**Issue by nwicki** [cmm-21/a6#28]
I just finished implementing task 8 and it seems to work just fine: https://youtu.be/_Gt32DcLySE

However, as you will see in the video posted above, it crashes (Segmentation fault 11, SIGSEGV) if I set the regularizer to -6.0 for the first time optimizing the objective. Has anyone else encountered this issue and maybe knows what is causing it?

**Comment by MiguelZamoraM** [comment]
See:  https://github.com/cmm-21/a6/issues/1,  https://github.com/cmm-21/a6/issues/10,  https://github.com/cmm-21/a6/issues/17
