### ISSUE TITLE
Images / Videos for Submission

### ISSUE THREAD

**Issue by benjirer** [cmm-21/a6#29]
Hey Miguel,

Could you quickly clarify what images/videos are required for the submission? In the write-up it is only mentioned that I need to upload a screenshot for exercise 7. Is that extensive or do you need more images/videos? 

Thank you!

**Comment by MiguelZamoraM** [comment]
Well if the write-up  only says you should update images for exercise 7,  I cannot expect you too upload images for other tasks. That being said, I would greatly appreciate if you add images and GIFs for other results that you have.

**Comment by benjirer** [comment]
Sure, will do! That's what I was thinking ;D
