### ISSUE TITLE
Crash after I clicked optimize in transcription method

### ISSUE THREAD

**Issue by catachiii** [cmm-21/a6#3]
(even for the unmodified file)
The building works fine without any errors or warnings using release mode and debug mode. 
I got an error running the app under debug mode. I am assuming that the optimizing process malfunctions somehow. 

```
File: C:/Users/cheng/Documents/GitHub/a6-Catially/build/_deps/eigen-src/Eigen/src/SparseLU/SparseLU.h, Line 220

Expression: m_factorizationIsOk && "The matrix should be factorized first"
```

**Comment by MiguelZamoraM** [comment]
See issue https://github.com/cmm-21/a6/issues/1
