### ISSUE TITLE
Transcription-app crashes when I run second-order optimizer

### ISSUE THREAD

**Issue by junja94** [cmm-21/a6#30]
Hi,

I just started `transcription-app` and having a weird issue.
I copy-pasted the `stepPhysicsExplicitEuler` function, run the app, and then toggled `optimize`.
As I didn't touch the objective yet, It should do nothing.

But when I run the optimizer, The optimizer just crashes with the following error message.

```
transcription-app: /home/jolee/git/a6-junja94/cmake-build-debug/_deps/eigen-src/Eigen/src/SparseLU/SparseLU.h:220: bool Eigen::SparseLU<_MatrixType, _OrderingType>::_solve_impl(const Eigen::MatrixBase<OtherDerived>&, Eigen::MatrixBase<OtherDerived>&) const [with Rhs = Eigen::Matrix<double, -1, 1>; Dest = Eigen::Matrix<double, -1, 1>; _MatrixType = Eigen::SparseMatrix<double>; _OrderingType = Eigen::COLAMDOrdering<int>]: Assertion `m_factorizationIsOk && "The matrix should be factorized first"' failed.
```

Any clue on what's happening here?

**Comment by junja94** [comment]
This is really weird. I restarted my PC and now it does not crash.
But still, sometimes it crashes...

**Comment by MiguelZamoraM** [comment]
I supposed you solved this issue.
