### ISSUE TITLE
Core Dumped error for transcription-app

### ISSUE THREAD

**Issue by kevinhangoat** [cmm-21/a6#31]
HI, sorry for the last minute question. For the transcription-app, if I optimize, it only shows Segmentation fault (core dumped), even when I wrote nothing. Is this happening because my algorithm is wrong or some steps are missing? I didn't have this bug in problem 1 for Newton's method. Thanks

**Comment by MiguelZamoraM** [comment]
Just check the issues: https://github.com/cmm-21/a6/issues?q=is%3Aissue+crash
