### ISSUE TITLE
No sound on tutorial video

### ISSUE THREAD

**Issue by nicolas-git** [cmm-21/a6#7]
I dont know if I'm doing something wrong but I have the impression that there is no sound on the tutorial video uploaded to the course website?

Thx in advance :D

**Comment by MiguelZamoraM** [comment]
Sorry for the inconvenience. This should't happen. Could you try playing the video with VLC player?

**Comment by nicolas-git** [comment]
Oh it works with VLC, I used quick time player before... Thank you :)
