### ISSUE TITLE
Q. 10, What is a perfect orbit?

### ISSUE THREAD

**Issue by meintte** [cmm-21/a6#8]
In the task description of the challenge app it's said to put the spaceship in a perfect orbit. My question is how much margin do we have? In my current implementation the spaceship touches the purple line all the time, but the orbit is still a bit elliptical. Is this okay, or do you have a maximal deviation of the target orbit which we should aim for?

**Comment by MiguelZamoraM** [comment]
The goal is to get right on the purple line, such that we can see a circular orbit like the one in the tutorial video (Min 19:56 Approx).
It sounds like you are on a good track already. Maybe it's just a matter of tuning your regularizes a bit more.
