### ISSUE TITLE
Q7 What is the expected Result

### ISSUE THREAD

**Issue by colincqian** [cmm-21/a6#9]
During the simulation in Q7, the planet in this section makes it hard to stop, and the spaceship will immediately fall to the planet after reaching the target (which is obvious). I wonder what we are expected to produce in this question. Are we supposed to only care about a successful optimized trajectory?

**Comment by MiguelZamoraM** [comment]
As long as the ship is at the target position in the last time step of the trajectory, you should be good. You should aim at getting a reasonable trajectory. A trajectory that jumps to the target in only one step  and then stays there is not very reasonable.
